"""empty message

Revision ID: 2b2e31f5e9ae
Revises: 6c220ff1f993
Create Date: 2020-04-04 00:56:49.496600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2e31f5e9ae'
down_revision = '6c220ff1f993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('art_shows', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artist', 'venue', ['art_shows'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'art_shows')
    # ### end Alembic commands ###
