"""empty message

Revision ID: eb1053b92ef8
Revises: 2b2e31f5e9ae
Create Date: 2020-04-04 01:29:35.682629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1053b92ef8'
down_revision = '2b2e31f5e9ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('art_shows', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'venue', 'artist', ['art_shows'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'art_shows')
    # ### end Alembic commands ###
